---
version: '3.7'
networks:
  internal:
    driver: bridge

services:
  asaserver:
    image: ghcr.io/camalot/ark-survival-ascended-server:latest
    hostname: asa_server
    container_name: asa_server
    restart: unless-stopped
    user: "1000:1000"
    networks:
      - internal
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4

    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago

      BATTLEEYE: 'FALSE'
      RCON_ENABLED: 'TRUE'
      MAP_NAME: 'TheIsland'

      DISPLAY_POK_MONITOR_MESSAGE: 'TRUE'
      UPDATE_SERVER: 'TRUE'
      CHECK_FOR_UPDATE_INTERVAL: 24
      RESTART_NOTICE_MINUTES: 30

      ENABLE_MOTD: 'FALSE'
      MOTD: ''
      MOTD_DURATION: 30

      SESSION_NAME: 'TACO'
      SERVER_ADMIN_PASSWORD: 'P@55vv0rD'
      SERVER_PASSWORD: ''
      ASA_PORT: 7777
      RCON_PORT: 27020
      MAX_PLAYERS: 20
      CLUSTER_ID: cluster
      MOD_IDS: ''
      CUSTOM_SERVER_ARGS: ''

      MAX_TAMED_DINOS: 1000

      # BAN_LIST_URL: 'http://nodered.local/ark/banlist'
      ALLOW_CHEATERS_UPDATE_INTERVAL: 600
      # ALLOW_CHEATERS_URL: 'http://nodered.local/ark/admins'

      # ENABLE_WHITELIST: TRUE
      # WHITELIST_URL: 'http://nodered.local/ark/whitelist'

      ENABLE_PVE: TRUE

    ports:
      - "27020:27020/tcp" # RCON
      - "7777:7777/tcp" # Game
      - "7777:7777/udp" # Game
      - "27015:27015/tcp" # Game
      - "27015:27015/udp" # Game
      - "27016:27016/tcp" # Game
      - "27016:27016/udp" # Game
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - "./data/asa:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame"
      - "./data/asa-server:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server"
      - "./data/cluster:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ShooterGame"
      - "./data/asa-data:/data"

    mem_limit: 16G
