---
name: Lint Helm Chart
on:
  push:
    branches:
      - "**" # All branches
      - "!gh-pages" # Except gh-pages
      - '!develop' # Except develop
      - '!main' # Except main
      - "!master" # Except master
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ github.token }}
